### 查询服务
GET http://127.0.0.1:9001/feather/skill-nacos-client/nacos-client/service-instance?serviceId=skill-gateway
Accept: application/json
skill-feather-user: eyJhbGciOiJSUzI1NiJ9.eyJza2lsbC1mZWF0aGVyLXVzZXIiOiJ7XCJpZFwiOjE2LFwidXNlcm5hbWVcIjpcImZlYXRoZXJcIn0iLCJqdGkiOiIyY2Q1YzVkOS1mM2QxLTRkZjItODRjNi1mNDA3NmI2M2ExMzkiLCJleHAiOjE3MDU3NjY0MDB9.R5UinT55_3emXqWBPTI5nEQX6iZe0R713Hnlpzmi7KWEfTs3aMPZCm-_wLoXhrrjoO-pnhZFJ3UNw5lvTigr5IzMAa-ew-JvWBoBg5R2BombcmjVMLdrsZdMEdzBUtErUU8pcAUKqdSBSmusLj4Based_x0OXIPvDzTYrU2bmcQs36Be9Y3GKcsgQvUh8UHgQRVIEY5lFidd_En5iuQGBi5sPax0qQPtrDsz5VbLOFf5b3IavFRgkOfSH4v1vCNO9EKBCrRZikkzC5uzhFkVAcZJiiXAqGiePX_TkajlLwRxHxOwtO7OFNOzFbFDYDpww7q6W3gHYxjLylhtp_b3pQ
token: feather
