### 获取 token
POST 127.0.0.1:8100/skill-sentinel-client/sentinel-fallback/get-token
Content-Type: application/json

{
  "username": "feather",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### 忽略异常
GET 127.0.0.1:8100/skill-sentinel-client/sentinel-fallback/ignore-exception?code=2
Content-Type: application/json
