### 获取当前用户余额信息
GET http://127.0.0.1:9001/feather/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiJmMWQ1YzBlOS0xMzgxLTQ2MDMtOTRkMC1iYjNhMjY4MWIwOWEiLCJleHAiOjE2OTIxMTUyMDB9.h85UjcOBO54SjHrDvsalj6ivftBbYVBeaHo46j5vueYe-563GY8EksQRE5aTQUNUYMvi7A0CudFmAy_e6Wx1l7vcOiQD7W2BTsqj9Psmidse5OwkqfvesHHMhDEmfQN8EIRDABWKuE64aC-grSR-sXHI7YsVLfOaxpLeAIfbkD7pl6TFcHOcNk5Uoxg5RpD8tPQ9YWcr-S5zBLc7gmrvQgHjUuVTylyxxVp7Xy3Tag3DczMhWpFTutUOjoUvq4XixShfJxCimrXQxDOui-zZ8jxXDuL1ouPCjHUDi8AOqOlbvVXsSVwno_jf2S8fw7q220QhqQrGTZJgcNvtsjwUeg

### 扣减用户余额
PUT http://127.0.0.1:9001/feather/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiJmMWQ1YzBlOS0xMzgxLTQ2MDMtOTRkMC1iYjNhMjY4MWIwOWEiLCJleHAiOjE2OTIxMTUyMDB9.h85UjcOBO54SjHrDvsalj6ivftBbYVBeaHo46j5vueYe-563GY8EksQRE5aTQUNUYMvi7A0CudFmAy_e6Wx1l7vcOiQD7W2BTsqj9Psmidse5OwkqfvesHHMhDEmfQN8EIRDABWKuE64aC-grSR-sXHI7YsVLfOaxpLeAIfbkD7pl6TFcHOcNk5Uoxg5RpD8tPQ9YWcr-S5zBLc7gmrvQgHjUuVTylyxxVp7Xy3Tag3DczMhWpFTutUOjoUvq4XixShfJxCimrXQxDOui-zZ8jxXDuL1ouPCjHUDi8AOqOlbvVXsSVwno_jf2S8fw7q220QhqQrGTZJgcNvtsjwUeg

{
  "userId": 10,
  "balance": 2000
}
